### ISSUE TITLE
Release 0.3.3 on PyPI

### ISSUE THREAD

**Issue by tiran** [latchset/kdcproxy#31]
I don't have permission to upload 0.3.3 on PyPI. You can use https://pypi.python.org/pypi/twine to upload the ```kdcproxy-0.3.3.tar.gz``` and ```kdcproxy-0.3.3-py2.py3-none-any.whl``` files from https://github.com/latchset/kdcproxy/releases/tag/v0.3.3

**Comment by frozencemetery** [comment]
Version 0.4 uploaded to pypi https://pypi.org/manage/project/kdcproxy/release/0.4/
