### ISSUE TITLE
class MITConfig uses non-existing boolean property

### ISSUE THREAD

**Issue by michael-o** [latchset/kdcproxy#48]
In

https://github.com/latchset/kdcproxy/blob/4bf616307f25d2cd2d53e34de247417f338355d2/kdcproxy/config/mit.py#L236-L238

the property `dns_fallback` is used, but the `krb5.conf` reference doc does not even mention it: https://web.mit.edu/kerberos/krb5-1.17/doc/admin/conf_files/krb5_conf.html

I assume you trying to mimic:

https://github.com/krb5/krb5/blob/09c9b7d6f64767429e90ad11a529e6ffa9538043/src/lib/krb5/os/locate_kdc.c#L42-L63

It deserves at least a comment in the code.

**Comment by frozencemetery** [comment]
Well, as your link illustrates, it very clearly exists, just as an undocumented property :)

MIT uses this value for testing.  This code was present in the original version of kdcproxy, but its documentation was removed in b409cba11db540cab85d18f3cde00e770728e8db.  I can't immediately see why we did that.

@npmccallum, git says you wrote that change (as well as the original version, of course).  Do you remember why we check this value?

**Comment by michael-o** [comment]
@frozencemetery, I'd expect to have a little bit more docs in  `README.md` as well as a note why `udp_preference_limit` is not necessary.

**Comment by frozencemetery** [comment]
Well, it is necessary for krb5, just not for kdcproxy (which is not krb5).  We don't mention `udp_preference_limit` at all in our docs.  There's no harm in setting it, from our perspective (unless, as you found, there's a bug somewhere else :) ).

**Comment by michael-o** [comment]
To conclude this, I think "Automatic Configuration" that the code will prefer TCP over UDP to avoid future user misunderstandings.
