### ISSUE TITLE
Obey MIT Kerberos udp_preference_limit

### ISSUE THREAD

**Issue by michael-o** [latchset/kdcproxy#49]
In our Active Directory environment UDP is not used, infact the KDC answers with:

```
 Received error from KDC: -1765328332/Antwort für UDP zu groß, erneuter Versuch mit TCP
```

Therefore, all servers are set to: `[libdefaults]/udp_preference_limit = 1`.

`kdcproxy.conf` is:

```
[global]
configs = mit
```

and `krb5 .conf` on the server where the KDC Proxy is running:

```
[libdefaults]
    default_realm = AD001.SIEMENS.NET
    forwardable = true
    canonicalize = true
    dns_lookup_kdc = true
    dns_uri_lookup = false
    rdns = false
    udp_preference_limit = 1

[domain_realm]
...
```

**Comment by michael-o** [comment]
It seems like that I am pretty much stuck because I see in Wireshark that the domain controller responds with `RESPONSE_TOO_BIG` on UDP.

**Comment by frozencemetery** [comment]
What version of kdcproxy is this?  How did you install it?

(In general, it's best to report error strings with `LC_ALL=C` set because that doesn't require stepping through the translation infrastructure in order to find source code.)

**Comment by michael-o** [comment]
Installed from Git master with `sudo pip install .` into Python 3.7 site packages and then hooked into `mod_wsgi`.

I almost all cases the Acitve Directory will report on UDP that the response paket size is too large for a datagram packet, this will happen again and then TCP is tried. This is basically waste of roundtrips. Therefore, the pref limit recommended by our AD admins. Similar issues for Microsoft Kerberos: https://support.microsoft.com/de-de/help/244474/how-to-force-kerberos-to-use-tcp-instead-of-udp-in-windows

**Comment by frozencemetery** [comment]
Is your KDC actually reachable using TCP?  (Please verify this using `kinit` from the webserver.)

Our sorting will prefer TCP to UDP by default: https://github.com/latchset/kdcproxy/blob/master/kdcproxy/__init__.py#L234-L239  (We intentionally don't check the config value.)

To debug further, I'm going to need to see the value you're getting from `addrs` there.  Ideally I'd also look at KDC logs, but if it's AD that's not going to help much.

**Comment by michael-o** [comment]
@frozencemetery Yes, it is. TCP works perfectly. Do you want the addresses before or after sorting and filtering?

**Comment by michael-o** [comment]
Thinking more about this, this may be also related due to the portability issue in KdcProxy which I have found today and have a simple fix for that. Stay tuned.

**Comment by michael-o** [comment]
OK, I know what happened now. Retested with #50 only TCP is used. Before the fix all KDC with TCP where exhausted because `EINPROGRESS` was incorrected checked and UDP was used. Therefore I received two DCs with UDP and saw "error response too big" in Wireshark.

`addrs`:

```
$ python3
Python 3.7.6 (default, Jan  8 2020, 08:45:21)
[Clang 8.0.1 (tags/RELEASE_801/final 366581)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> def __filter_addr(addr):
...     if addr[0] not in (socket.AF_INET, socket.AF_INET6):
...         return False
...     if addr[1] not in (socket.SOCK_STREAM, socket.SOCK_DGRAM):
...         return False
...     if addr[2] not in (socket.IPPROTO_TCP, socket.IPPROTO_UDP):
...         return False
...     return True
...
>>> addrs = socket.getaddrinfo("ad001.siemens.net", 88)
>>> addrs = tuple(sorted(filter(__filter_addr, addrs), key=lambda a: a[2]))
>>> addrs
((<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.239', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.71', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.217', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.233', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.201', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.199', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.231', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.215', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.235', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.237', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('129.103.99.57', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.239', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.71', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.217', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.233', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.201', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.199', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.231', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.215', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.235', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.237', 88)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('129.103.99.57', 88)))
>>>
```

**Comment by frozencemetery** [comment]
Awesome, I'll close this in favor of #50 then.

**Comment by frozencemetery** [comment]
Follow-up: I'm a bit impressed this works on non-Linux at all.  We certainly never tested it there.

**Comment by michael-o** [comment]
> 
> 
> Follow-up: I'm a bit impressed this works on non-Linux at all. We certainly never tested it there.

Why shouldn't it? Decent portable Python code should work everywhere. I plan to create a FreeBSD port for that next month as soon as this starts to work/be connectable on/from our GitLab runners.
